package neuron_based.layers;

import neuron_based.neurons.*;

/**
 * This is an extension of Layer and is used as an InputLayer (the first Layer)
 * in a NeuronBasedNeuralNetwork.
 * 
 * @author OdinhengeT
 * @see NeuronBasedNeuralNetwork
 * @see NeuronLayer
 * @see InnerNeuronLayer
 * @see OutputNeuronLayer
 * @see Neuron
 */
public class InputNeuronLayer extends NeuronLayer {

	/**
	 * Creates an InputLayer with nbrNeurons Neurons (excluding BiasNeuron), each
	 * with nbrLinks links.
	 * 
	 * @param nbrNeurons number of Neurons excluding BiasNeuron
	 * @param nbrLinks   number of links of each Neuron
	 */
	public InputNeuronLayer(int nbrNeurons, int nbrLinks) {
		super(nbrNeurons, nbrLinks);
		neurons = new Neuron[nbrNeurons + 1]; // Add one for the BiasNeuron
		for (int i = 0; i < neurons.length; i++) {
			neurons[i] = new InputNeuron(nbrLinks);
			neurons[i].createWeights(nbrNeurons);
		}
		neurons[nbrNeurons] = new BiasNeuron(nbrLinks);
		neurons[nbrNeurons].createWeights(nbrNeurons);
	}

	/**
	 * Returns the output generated by this InputLayer, an array containing the sum
	 * of each of the Neurons outputs in this layer to each Neuron in the next.
	 * 
	 * @return output of this Layer
	 */
	public double[] getOutput() {
		double[] output = new double[nbrLinks];
		for (Neuron n : neurons) {
			for (int i = 0; i < nbrLinks; i++) {
				output[i] += n.getOutputTo(i);
			}
		}
		return output;
	}

	/**
	 * Returns a String representation of this InputLayer.
	 * 
	 * @return a String describing this Layer
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder("InputLayer: ");
		for (Neuron n : neurons) {
			sb.append(n.toString());
		}
		return sb.toString();
	}

}
